#!/bin/bash

serverIp=192.168.124.254
serverUser=openhab
serverPassword="openhab"
serverOpenhabPath="/etc/openhab/"

localOpenhabPath="$PWD/openhab/"

folderArray=(
#    "html/"
#    "icons/"
    "items/"
    "persistence/"
    "rules/"
#    "scripts/"
#    "services/"
    "sitemaps/"
#    "sounds/"
    "things/"
#    "transform/"
    )

for folder in "${folderArray[@]}"
do
    echo "Update Source: $localOpenhabPath$folder Destination: $serverOpenhabPath$folder"
	sshpass -p $serverPassword ssh $serverUser@$serverIp "rm -f $serverOpenhabPath$folder*"
    sshpass -p $serverPassword scp $localOpenhabPath$folder* $serverUser@$serverIp:$serverOpenhabPath$folder
    sshpass -p $serverPassword ssh $serverUser@$serverIp "chmod a=rwx $serverOpenhabPath$folder*"
done

# Restart service?