- name: Set timezone
  tags: install,never
  community.general.timezone:
    name: "{{ system_timezone }}"

- name: Extend the logical volume to consume all remaining space in the volume group
  community.general.lvol:
    vg: ubuntu-vg
    lv: ubuntu-lv
    size: +100%FREE
    resizefs: true

- name: Stop/disable service openipmi
  systemd_service:
    name: openipmi
    state: stopped
    enabled: false

- name: Stop/disable service systemd-networkd-wait-online
  systemd_service:
    name: systemd-networkd-wait-online
    state: stopped
    enabled: false
    masked: true
