{
 "title": "Consumer",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Time of day",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 22, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Solar Phase",
     "measurement": "timeOfDay",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Inverter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "filtered_power_inverter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "filtered_power_grid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Consumption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "filtered_power_consumption",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Trigger",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "alias": "Dehumidifier",
     "groupBy": [
      { "params": [ "value::field" ], "type": "tag" }
     ],
     "measurement": "dehumidifier_trigger",
     "query": "SELECT \"value\" FROM \"dehumidifier_trigger\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Boiler LOW",
     "measurement": "boiler_33_percent_trigger",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Boiler FULL",
     "measurement": "boiler_100_percent_trigger",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consumer",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "alias": "Dehumidifier",
     "groupBy": [
      { "params": [ "value::field" ], "type": "tag" }
     ],
     "measurement": "dehumidifier_switch",
     "query": "SELECT \"value\" FROM \"dehumidifier_trigger\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Boiler Phase 1",
     "measurement": "boiler_phase1_switch",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Boiler Phase 2",
     "measurement": "boiler_phase2_switch",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Boiler Phase 3",
     "measurement": "boiler_phase3_switch",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}