{
 "title": "Long term day",
 "time": { "from": "now-16d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Household Cash Flow",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyCHF" } },
   "targets": [
    {
     "alias": "Energy purchasing",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "paid_money_consumption_grid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tz": "Europe/Zurich"
    },
    {
     "alias": "Energy Self-Use (Saving)",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "saved_money_consumption",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tz": "Europe/Zurich"
    },
    {
     "alias": "Energy Sale",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "received_money_returned_grid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tz": "Europe/Zurich"
    }
   ]
  },
  {
   "title": "Energy Inverter",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Energy Inverter",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Energy_Inverter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tz": "Europe/Zurich"
    }
   ]
  },
  {
   "title": "Household Energy Consumption",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Energy Grid",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Energy_Grid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tz": "Europe/Zurich"
    },
    {
     "alias": "Energy Self Consumption",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Energy_Self_Consumption",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tz": "Europe/Zurich"
    }
   ]
  },
  {
   "title": "Energy Grid",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Energy Sale",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Energy_Returned_Grid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "* -1" ], "type": "math" }
      ]
     ],
     "tz": "Europe/Zurich"
    },
    {
     "alias": "Energy Purchase",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Energy_Grid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tz": "Europe/Zurich"
    }
   ]
  },
  {
   "title": "Degree of Autonomy",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Degree of Autonomy",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "Day_Degree_Of_Autonomy",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "Europe/Zurich"
    }
   ]
  },
  {
   "title": "Self Consumption",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Self Consumption",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "Day_Rate_Self_Consumption",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "Europe/Zurich"
    }
   ]
  }
 ]
}