{
 "title": "Long term year",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Energy Inverter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Energy Inverter",
     "measurement": "Energy_Inverter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "Europe/Zurich"
    }
   ]
  },
  {
   "title": "Household Cash Flow",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyCHF" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Energy Grid",
     "measurement": "paid_money_consumption_grid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "Europe/Zurich"
    },
    {
     "alias": "Energy Self-Use",
     "measurement": "saved_money_consumption",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "Europe/Zurich"
    },
    {
     "alias": "Energy Sale",
     "measurement": "received_money_returned_grid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "Europe/Zurich"
    }
   ]
  },
  {
   "title": "Household Energy Consumption",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Energy Grid",
     "measurement": "Energy_Grid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "Europe/Zurich"
    },
    {
     "alias": "Energy Self-Use",
     "measurement": "Energy_Self_Consumption",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "Europe/Zurich"
    }
   ]
  },
  {
   "title": "Energy Grid",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Energy Sale",
     "measurement": "Energy_Returned_Grid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "Europe/Zurich"
    },
    {
     "alias": "Energy Grid",
     "measurement": "Energy_Grid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "Europe/Zurich"
    }
   ]
  }
 ]
}