{
 "title": "Tariff",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Tariff",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 22, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "EKZ",
     "measurement": "tariff",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Returned Energy Today",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "High Tariff",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "Energy_Returned_Grid_High_Tariff",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    },
    {
     "alias": "Low Tariff",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "Energy_Returned_Grid_Low_Tariff",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consumption Energy Today",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "High Tariff",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "Energy_Consumed_Grid_High_Tariff",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    },
    {
     "alias": "Low Tariff",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "Energy_Consumed_Grid_Low_Tariff",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Received Money Today",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyCHF" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "High Tariff",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "received_money_returned_grid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Paid Money Today",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 11, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyCHF" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "High Tariff",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "paid_money_consumption_grid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Household",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Consumption",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Day_Energy_Grid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    },
    {
     "alias": "Returned",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Day_Energy_Returned_Grid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    }
   ]
  }
 ]
}