- name: Install AWS CLI using snap
  snap:
    name: aws-cli
    classic: yes
    state: present

- name: copy leg systemd service
  copy:
    src: service/
    dest: /etc/systemd/system/
    mode: '0644'

- name: leg script
  copy:
    src: shell/
    dest: /usr/local/bin/
    mode: '0744'

- name: reload systemd daemon
  command: systemctl daemon-reload

- name: activate leg service
  systemd:
    name: leg
    enabled: yes
    state: restarted

- name: activate leg service
  systemd:
    name: leg.timer
    enabled: yes
    state: restarted
