---

- hosts: all
  become: true

  pre_tasks:
    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest
        update_cache: yes

  roles:
    - role: system_settings
      tags: install,never

    - role: influxdb_install
      tags: install,never

    - role: prometheus_install
      tags: install,never

    - role: grafana_install
      tags: install,never

    - role: java_install
      tags: install,never

    - role: openhab_install
      tags: install,never

    - role: file_copy
      tags: copy

    - role: leg_service
      tags: leg
